apiVersion: apps/v1
kind: Deployment
metadata:
  name: gancio
spec:
  selector:
    matchLabels:
      app: gancio
  replicas: 1
  template:
    metadata:
      labels:
        app: gancio
    spec:
      containers:
        - name: gancio
          image: cisti/gancio
          env:
            - name: GANCIO_DATA
              value: "/home/node/data"
            - name: GANCIO_DB_DIALECT
              value: "postgres"
            - name: GANCIO_DB_HOST
              value: "postgres"
            - name: GANCIO_DB_PORT
              value: "5432"
            - name: GANCIO_DB_DATABASE
              value: "gancio"
            - name: GANCIO_DB_USERNAME
              value: "gancio"
            - name: GANCIO_DB_PASSWORD
              value: "gancio"
            - name: GANCIO_PORT
              value: "13120"
          ports:
            - containerPort: 13120
          volumeMounts:
            - mountPath: /home/node/data
              name: gancio-data
          resources:
            limits:
              memory: "2048Mi"
              cpu: "1000m"
      volumes:
        - name: gancio-data
          persistentVolumeClaim:
            claimName: gancio-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: gancio
spec:
  selector:
    app: gancio
  ports:
    - protocol: TCP
      port: 13120
      targetPort: 13120
      nodePort: 31320
  type: NodePort
