apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  storageClassName: postgres-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/eduard/hsp/gancio/data-kubernetes/postgres/"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gancio-data-pv
spec:
  storageClassName: gancio-storage
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/eduard/hsp/gancio/data-kubernetes/gancio-data/"
